spring:
  application:
    name: task-sie-services
  profiles:
    include:
      - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/sie-gestor-tareas-desarrollo
    username: postgres
    password: system
  jpa:
    properties:
      hibernate:
        format_sql: false
        default_schema: public
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/dbchangelog.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${PORT:8080}
  servlet:
    contextPath: /api
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

